### ISSUE TITLE
Docs for ConfigService, Interconnection, i18n-Examples

### ISSUE THREAD

**Issue by mickbigblue** [Daimler/mo360-ftk#16]
Hi,

Thanks for the great work on this toolkit.

As I'm currently beginning to implement a web-app using the mo360-ftk, I'd like to ask if there are any plans to "fill in" the documentation in the near future. Particularly the parts `ConfigService`, `Interconnection` and `i18n-Examples` would be of interest.

Thanks in advance.

mick

**Comment by prode81** [comment]
Hey Mick,

thanks for your feedback ;)
Yes, of course, we are planning to fill in the gaps within the documentation, as soon, as we can spare the time.
Until then, fill free to drop any question, you might have.

Cheers,
Paul

**Comment by mickbigblue** [comment]
Impressive response time :-)

All right, I'll get in touch with you guys if I get stuck. Just wanted to clear things upfront.

Thanks again.
