### ISSUE TITLE
Material Design and FTK

### ISSUE THREAD

**Issue by relianz** [Daimler/mo360-ftk#17]
My team has the impression that Daimler currently favors [Material Design](https://material.io/design), there is also a specific component library for this (Daimler UI, based on library [Material-UI](https://github.com/mui-org/material-ui)). If we use FTK in a greenfield project for Daimler, is that okay?

**Comment by prode81** [comment]
Of course it is okay and even welcome.

If you have access to internal resources (git, artifactory), just run:
npx @switch/create-app appName

It will automatically download the FTK and add the Daimler Theme and Fonts to your project.
