### ISSUE TITLE
injects in swidgets got lost

### ISSUE THREAD

**Issue by farion** [Daimler/mo360-ftk#18]
Hi all,

**Issue**

If a custom service is injected in a swidget, it can not be resolved if the same swidget was unloaded somewhere else.

Error Message:
`Error: Can't inject testService as no binding for type function TestService() { _classCallCheck(this, TestService); } was found. Did you register it in the DiContainer?`

**Minimal example**

As this happens in several tricky situations, I tried a minimal example: https://github.com/farion/test-mo360-ftk/tree/INJECT_ISSUE

- Go to host
- Run "npm run start:host"
- Go to swidget
- Run "npm run start:swidget"
- Navigate to http://localhost:8888"
- Proceed with steps to reproduce.

**What is in the minimal example?**

Basically I have a host app and a swidget, which exists twice on a page. Each can be toggled with a button.
If a swidget is toggled, everything is rerendered. There is a service in the swidget, that is registered to the container in the init method. This service just produces a time string. The Home component in the swidget injects the service and displays that time string.

Basically this is working. But if I unload the second swidget, the first is not able to inject the service anymore.

**Steps to reproduce:**
- Show first Swidget
- Show second Swidget
- Hide second Swidget
- First swidget will be unable to inject the service with the above message.

I debugged this and found out, that the service still is bound to the container in the inject call, but can not be found anymore due to missing propertyKey. 
Nevertheless if I use a named inject `@inject("test")` the problem does not exist.

**Here is a video to show the steps:**

https://user-images.githubusercontent.com/280686/103003743-a80bed00-4531-11eb-9711-b864d1d31564.mov

Best,
farion

**Comment by prode81** [comment]
Hello @farion,

happy new year and thank you for your detailed issue-report.
We appreciate the effort you put into this and will look into this issue as soon as possible.

Due to holiday season, it might take a while, but we will keep you updated.

Cheers,
Paul

---
Acting on behalf of Daimler TSS GmbH.

**Comment by janstoecklin** [comment]
+1

**Comment by prode81** [comment]
A core-developer is assigned to take care of this issue. We keep you informed about any progress.
___
Acting on behalf of Daimler TSS GmbH.

**Comment by farion** [comment]
+1

**Comment by BlackDark** [comment]
@farion error still persists with `0.3.3`

**Comment by farion** [comment]
Sorry I did not expect to reopen the ticket. We currently checking if 0.3.3 fixes the problem. I will keep you informed.

**Comment by prode81** [comment]
@farion Make sure, that you use a unique uniqueID for each Swidget within your application.
In your example, both Swidgets hat the same ID.

**Comment by BlackDark** [comment]
@fafa0803 push

**Comment by farion** [comment]
@BlackDark Sorry for the late answer. In the meantime, we checked the issue and it is fixed. We were able to remove our workaround. Thank you. Please close the ticket again.
