### ISSUE TITLE
Can FTK be used with react 17?

### ISSUE THREAD

**Issue by btmnk** [Daimler/mo360-ftk#33]
Currently the package.json of the core states in its peerDepdencies that react `>=16.9.0 <17.0.0` is expected.
Is there any particular reason why it wouldn't work with React 17?
AFAIK React 17 didn't introduce any new features and no breaking changes as well but instead helps to prepare for a step-by-step migration to new breaking changes in React 18 (see https://reactjs.org/blog/2020/10/20/react-v17.html#gradual-upgrades).

If it is possible to use React 17 with the current FTK boilerplate would it be possible to change the semver for the peerDependencies of the core from `"react": ">=16.9.0 <17.0.0",` to `"react": "^16.9.0 || ^17.0.0",`?

**Comment by BlackDark** [comment]
Good point, should also work with 17. Will change it 👍
