### ISSUE TITLE
Github Pages for Demo Page

### ISSUE THREAD

**Issue by lucidlemon** [Daimler/mo360-ftk#5]
Hi there,

are you open to releasing a [Github Pages](https://pages.github.com) branch so that some components could be demoed without requiring to install everything locally?

**Comment by prode81** [comment]
Hey @lucidlemon,

we're open for any suggestion ;)
What should be part for the demo from your perspective?
The Boilerplate itself seems underwhelming for it.

-------------------------------------------------------------------------------------------------------------
Acting on behalf of [Daimler TSS GmbH](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md).

**Comment by prode81** [comment]
Closed for now. We keep this suggestion in mind for later.
