### ISSUE TITLE
What is MO360?

### ISSUE THREAD

**Issue by btmnk** [Daimler/mo360-ftk#7]
I just wondered what the MO360 in the library name means and couldn't find anything in the docs. 
I think it would be nice to have a small explanation for its meaning to make the name more memorable and associatable.

Best Regards,
btmnk

**Comment by jlinkohr** [comment]
Maybe the following video gives a little bit of an overview what MO360 is: https://media.mercedes-benz.com/meetmercedesdigital?video=a1f99cc1-a369-45c1-b175-b9c59fb52914
